// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs4210MmdGBwUtjwMXlcrXYGjT8_hh6ro',
    appId: '1:787802477806:web:e318cc1090acffd91e0fff',
    messagingSenderId: '787802477806',
    projectId: 'flutter-study-app-31ec4',
    authDomain: 'flutter-study-app-31ec4.firebaseapp.com',
    storageBucket: 'flutter-study-app-31ec4.appspot.com',
    measurementId: 'G-34KW6KDR0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH6-8l0lNSDJQy0fChvmM9vp5gSrE4xlA',
    appId: '1:787802477806:android:06f074372bf6cb371e0fff',
    messagingSenderId: '787802477806',
    projectId: 'flutter-study-app-31ec4',
    storageBucket: 'flutter-study-app-31ec4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx2mQHKTyfTqa58W5-bSvGeav8vl4phbg',
    appId: '1:787802477806:ios:fdda899400f638011e0fff',
    messagingSenderId: '787802477806',
    projectId: 'flutter-study-app-31ec4',
    storageBucket: 'flutter-study-app-31ec4.appspot.com',
    iosClientId: '787802477806-94d7m4e7v5bhbahlq5q8be27hnf61kp0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStudyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx2mQHKTyfTqa58W5-bSvGeav8vl4phbg',
    appId: '1:787802477806:ios:fdda899400f638011e0fff',
    messagingSenderId: '787802477806',
    projectId: 'flutter-study-app-31ec4',
    storageBucket: 'flutter-study-app-31ec4.appspot.com',
    iosClientId: '787802477806-94d7m4e7v5bhbahlq5q8be27hnf61kp0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStudyApp',
  );
}
